sudo: required
dist: trusty
language: node_js

env:
  matrix:
    - NODE_VERSION="8" NPM_VERSION="6"
    - NODE_VERSION="9" NPM_VERSION="6"
    - NODE_VERSION="10" NPM_VERSION="6"

before_install:
  - pip install --user codecov
  # Prepare node and npm
  - nvm install $NODE_VERSION && nvm use $NODE_VERSION
  - npm install -g npm@$NPM_VERSION
  - npm install

before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"

script:
  - npm run build
  - npm run check
  - npm test

after_success:
  - ./node_modules/.bin/codecov  -f coverage/coverage-final.json

addons:
  chrome: stable
  firefox: "42.0"
  apt:
    sources:
    - ubuntu-toolchain-r-test
    # required by node-gyp to build some packages
    packages:
    - g++-4.8
